disable tests on R 3.4 because of pandoc issue
* creating vignettes ... ERROR
Error: Error: processing vignette 'applications.Rmd' failed with diagnostics:
could not find function "pandoc_math_engines"
Execution halted
Error: Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.